### ISSUE TITLE
Crashes Game when dying to void in different dimensions

### ISSUE THREAD

**Issue by paulmarenbach** [friedkeenan/baby-powder#1]
It seems like you didn't put in a handle for deaths caused by the void (tested in the Overworld, but also in non vanilla scenarios i.e. the Eden Ring Mod), the killer is null and it produces the following exception, which crashes the game:
The game crashed whilst ticking player
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.method_5864()" because "killer" is null
caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.method_5864()" because "killer" is null
	at net.minecraft.class_3222.handler$zml000$trackBabiesKilled(class_3222.java:4270) ~[client-intermediary.jar:?]

I hope you can fix this issue, because I really like this mod idea :)

Best Whishes
Paul

**Comment by friedkeenan** [comment]
Hmm, I'm having trouble reproducing this (though I can see in the code where the bug is, and that it is a bug). I'd like to be able to reproduce this so I can know I've fixed it. Could you explain to me the steps you're taking to trigger this crash?

**Comment by friedkeenan** [comment]
@DieFetteBrxnette Please get back to me on how to reproduce this issue, but also in the meantime if you could test this build of the mod and tell me if the issue is resolved I would greatly appreciate it.


[test-build.zip](https://github.com/friedkeenan/baby-powder/files/9056056/test-build.zip)

**Comment by paulmarenbach** [comment]
I can't seem to reproduce this issue with just the mod again. (I thought I had tested it with just the mod, oops), so it's probably an incompatibility with another mod, sorry that I assumed it was only caused by this mod, but perhaps you could just add a simple return statement, if the killer is null? I also am not really able to figure out, what mod is incomatible with yours, sorry for that. Greate mod tho.
When testing with my mods, the error still persists even with the new build.

**Comment by friedkeenan** [comment]
What other mods are you using?

**Comment by paulmarenbach** [comment]
I made a small modpack for myself with about 190 jar files, loaded it gets to 310 mods. I have some mods in my mind that might cause the issue and I wanted to test them later.

**Comment by friedkeenan** [comment]
Oh wait I'm able to reproduce it. I thought the issue was babies being killed by the void, but really it's players being killed by the void. Should be an easy fix!

**Comment by friedkeenan** [comment]
Thank you for reporting this!
